language: python
  - "3.8"

services:
  - mysql

env:
  global:
    - TRAVIS=true

before_install:
  - mysql -u root --password="" < test/hamo_records_test_db.sql

install:
  - pip install -r requirements.txt

script:
  - python unit_test.py